<?php


/**
 * Implements hook_init().
 */
function geofield_gmap_widget_init() {
  // drupal_add_js('http://maps.google.com/maps/api/js?sensor=false', 'external');
  // drupal_add_js(drupal_get_path('module', 'geofield_gmap_widget') . '/map.js');
}


/**
 * Implements hook_field_widget_info().
 */
function geofield_gmap_widget_field_widget_info() {
  return array(
    'geofield_gmap' => array(
      'label' => t('Google map'),
      'field types' => array('geofield'),
    ),
  );
}


/**
 * Implements hook_field_widget_form().
 */
function geofield_gmap_widget_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $widget = $instance['widget'];
  $settings = $widget['settings'];
  $element = geofield_get_base_element($element, $items, $delta);

  switch ($instance['widget']['type']) {
    case 'geofield_gmap':
      $element['master_column']['#value'] = 'latlon';
      $element['map'] = array(
        '#markup' => '<div id="geofield-gmap-widget-canvas" style="height: 400px"></div>',
        '#weight' => 0,
      );
      $element['lat'] = array(
        '#type' => 'textfield',
        '#title' => t('Latitude'),
        '#default_value' => isset($items[$delta]['lat']) ? $items[$delta]['lat'] : '',
        '#prefix' => '<div class="geofield-gmap-widget-latitude">',
        '#suffix' => '</div>',
        '#weight' => 1,
      );
      $element['lon'] = array(
        '#type' => 'textfield',
        '#title' => t('Longitude'),
        '#default_value' => isset($items[$delta]['lon']) ? $items[$delta]['lon'] : '',
        '#prefix' => '<div class="geofield-gmap-widget-longitude">',
        '#suffix' => '</div>',
        '#weight' => 1,
      );
      $element['#attached']['js'][] = array(
        'data' => 'http://maps.google.com/maps/api/js?sensor=false',
        'type' => 'external',
      );
      $element['#attached']['js'][] = array(
        'data' => drupal_get_path('module', 'geofield_gmap_widget') . '/map.js',
        'type' => 'file',
      );
      break;
  }
  return $element;
}
